version: '3.8'

services:
  # Safe mode - isolated container without USB access
  fridapk-safe:
    image: ghcr.io/sudo-tiz/fridapk:latest
    # Fallback to local build if image not available
    build: .
    volumes:
      - ./workspace:/home/fridapk/workspace
    working_dir: /home/fridapk
    command: bash
    stdin_open: true
    tty: true
    environment:
      - FRIDAPK_MODE=safe
    profiles:
      - safe
      - all

  # Device access mode - with USB access for real device testing
  fridapk-usb:
    image: ghcr.io/sudo-tiz/fridapk:latest
    # Fallback to local build if image not available
    build: .
    volumes:
      - ./workspace:/home/fridapk/workspace
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /home/fridapk
    privileged: true
    devices:
      - /dev/bus/usb
    command: bash
    stdin_open: true
    tty: true
    environment:
      - FRIDAPK_MODE=usb
    profiles:
      - usb
      - all
