---
name: fridapk

services:
  # Safe mode - isolated container without USB access
  fridapk-safe:
    image: ghcr.io/sudo-tiz/fridapk:latest
    # Fallback to local build if image not available
    build:
      context: .
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    user: "${UID:-1000}:${GID:-1000}"
    command: bash
    stdin_open: true
    tty: true
    environment:
      - FRIDAPK_MODE=safe
      - FRIDAPK_GADGETS_DIR=/fridapk/gadgets

  # Device access mode - with USB access for real device testing
  fridapk-usb:
    image: ghcr.io/sudo-tiz/fridapk:latest
    # Fallback to local build if image not available
    build:
      context: .
    volumes:
      - ./workspace:/workspace
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /workspace
    user: "${UID:-1000}:${GID:-1000}"
    privileged: true
    devices:
      - /dev/bus/usb
    command: bash
    stdin_open: true
    tty: true
    environment:
      - FRIDAPK_MODE=usb
      - FRIDAPK_GADGETS_DIR=/fridapk/gadgets

  # Development mode - mount source code for live editing
  fridapk-dev:
    image: fridapk-local
    # Build locally for development
    build:
      context: .
    volumes:
      - ./workspace:/workspace
      - ./src:/fridapk/src
      - ./fridapk:/fridapk/fridapk
    working_dir: /workspace
    user: "${UID:-1000}:${GID:-1000}"
    command: bash
    stdin_open: true
    tty: true
    environment:
      - FRIDAPK_MODE=safe
      - FRIDAPK_GADGETS_DIR=/fridapk/gadgets
      - PYTHONPATH=/fridapk/src
